// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_mainwindow.cpp"
#include "UVLADIE3JM/moc_ollamaclient.cpp"
#include "UVLADIE3JM/moc_pythonexecutor.cpp"
#include "UVLADIE3JM/moc_workerthread.cpp"
